### ISSUE TITLE
Quiz response randomisation

### ISSUE THREAD

**Issue by SimonAMcKenzie** [ClaireFraser121/tbt-education-app#68]
AS a developer
I WANT the quiz responses from the JSON file randomised at all times
SO THAT the user can get the most out of the quiz 

- [x] Research how to use math.random method to randomise order of quiz responses
- [ ] Would it work if the responses were generated using a seperate component

**Comment by partialarts** [comment]
Thanks @SimonAMcKenzie will take a look over the weekend.

**Comment by SimonAMcKenzie** [comment]
Hi @partialarts checking of there have been any updates regards the quiz response randomisation? If there have been any challenges/roadblocks let me know, and we can arrange time to go through it together.

**Comment by partialarts** [comment]
Hi @SimonAMcKenzie all sorted by randomising the questions and resulting answers array at the API call stage.
